config:
  MD001: false
  MD045: false
  MD010: false
  MD012: false
  MD004: false
  MD026: false
  MD031: false
  MD034: false
  MD041: false
  MD033: false
  MD013: false
  MD037: false
  MD022: false
  MD009: false
  MD032: false
  MD013: false
