-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE NE135A1M-NY1",
  mode = "2880x1920@120.00",
  position = "0x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "4", monitor = "desc:BOE NE135A1M-NY1" })
hl.workspace_rule({ workspace = "5", monitor = "desc:BOE NE135A1M-NY1" })
