#!/bin/bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="wofi"

# Options
screen=" Whole Desktop"
area=" Selected Area"
window=" Focused Window"

# Variable passed to rofi
options="$screen\n$area\n$window"

chosen="$(echo -e "$options" | $rofi_command -p 'Take A Shot' -dmenu -selected-row 1)"
case $chosen in
  $screen)
    sleep 1; scrot 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES)/Screenshots ; imv $$(xdg-user-dir PICTURES)/Screenshots/$f'
    ;;
  $area)
    grim -g "$(slurp)" - | swappy -f -
    ;;
  $window)
    sleep 1; scrot -u 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES)/Screenshots ; imv $$(xdg-user-dir PICTURES)/Screenshots/$f'
    ;;
esac

