version = 1

[picker]
show_icons = true
show_path = true
show_preview = true

[workspace_defaults]
preview = "eza --icons=always --color=always -la {}"

# [[workspace]]
# name = "Example"
# path = "~/projects/example"
