-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "2560x1600@240.00", position = "512x1472", scale = 1.60 })
hl.monitor({ output = "DP-4", mode = "2560x1440@74.97", position = "0x0", scale = 1.00 })
hl.monitor({ output = "DP-5", mode = "2560x1440@74.97", position = "2560x0", scale = 1.00 })
