-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0A3B",
  mode = "2560x1600@240.00",
  position = "512x1472",
  scale = 1.6,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG IPS QHD 303NTLE28728",
  mode = "2560x1440@74.97",
  position = "2560x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG IPS QHD 303NTSU28726",
  mode = "2560x1440@74.97",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Electronics LG IPS QHD 303NTSU28726", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Electronics LG IPS QHD 303NTSU28726" })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Electronics LG IPS QHD 303NTLE28728" })
hl.workspace_rule({ workspace = "4", monitor = "desc:BOE 0x0A3B" })
hl.workspace_rule({ workspace = "5", monitor = "desc:BOE 0x0A3B" })
