#!/bin/bash

# term=alacritty
term=kitty
rofi_command="rofi -theme themes/launcher.rasi"

sessions=$(tmux ls | sed -e 's/^\([^:]*\).*/\1/g')

chosen="$(echo -e "$sessions" | $rofi_command -p "TMUX sessions" -dmenu -selected-row 0)"

[[ ! -z "$chosen" ]] && $term -e tmux new-session -A -s $chosen
