return {
	-- {
	-- 	"RRethy/base16-nvim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require('base16-colorscheme').setup({
	--
	-- 			base00 = '#1d2021',
	-- 			base01 = '#141617',
	-- 			base02 = '#282828',
	-- 			base03 = '#7a7c73',
	-- 			base0B = '#e3d166',
	-- 			base04 = '#bdbfb3',
	-- 			base05 = '#fdfff8',
	-- 			base06 = '#fdfff8',
	-- 			base07 = '#fdfff8',
	-- 			base08 = '#f5a699',
	-- 			base09 = '#f5a699',
	-- 			base0A = '#bbc87c',
	-- 			base0C = '#f5fecb',
	-- 			base0D = '#bbc87c',
	-- 			base0E = '#dfeca2',
	-- 			base0F = '#dfeca2',
	-- 		})
	--
	-- 		local current_file_path = vim.fn.stdpath("config") .. "/lua/plugins/dankcolors.lua"
	-- 		if not _G._matugen_theme_watcher then
	-- 			local uv = vim.uv or vim.loop
	-- 			_G._matugen_theme_watcher = uv.new_fs_event()
	-- 			_G._matugen_theme_watcher:start(current_file_path, {}, vim.schedule_wrap(function()
	-- 				local new_spec = dofile(current_file_path)
	-- 				if new_spec and new_spec[1] and new_spec[1].config then
	-- 					new_spec[1].config()
	-- 					print("Theme reload")
	-- 				end
	-- 			end))
	-- 		end
	-- 	end
	-- }
}
