return {
  -- {
  --   "Mofiqul/dracula.nvim",
  --   init = function()
  --     require('dracula').setup {
  --       italic_comment = true,
  --     }
  --   end,
  -- },
  -- {
  --   "marko-cerovac/material.nvim",
  --   init = function()
  --     vim.g.material_style = "deep ocean"
  --   end,
  -- },
  -- {
  --   "theRealCarneiro/hyprland-vim-syntax",
  --   dependencies = { "nvim-treesitter/nvim-treesitter" },
  --   ft = "hypr",
  -- },
  -- lsp = {
  --   formatting = {
  --     format_on_save = true,
  --   },
  -- },
}
