"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
# [╭╴](238)[](bold white) \
# $all[╰─](238)$character"""
# format = """\
# [╭╴](bold cyan)[ ](bold cyan) \
# [╭╴](bold cyan)[ ](bold cyan) \
# $jobs$username@$hostname$directory$git_branch$git_status$line_break[╰─](bold cyan)$character"""
# [╭╴](bold cyan)[ ](bold cyan) \
format = """
[╭╴](color_primary)\
[](color_primary)\
$os\
$hostname\
[ ](bg:none fg:color_primary)\
$jobs\
$directory\
$git_branch\
$git_status\
$azure\
$terraform\
$nix_shell\
$python\
$line_break\
[╰─](color_primary)$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#36074d'
color_red = '#cc241d'
color_yellow = '#d79921'
color_primary = '#d65d0e'

# Change the default prompt characters
[character]
# success_symbol = "[󰁔](color_primary)"
# success_symbol = "[](color_primary)"
# success_symbol = "[󰐊](color_primary)"
success_symbol = "[󰄾](color_primary)"
# success_symbol = "[](color_primary)"
error_symbol = "[󰄾](color_red)"
# error_symbol = "[󰐊](color_red)"
# error_symbol = "[](color_red)"
# error_symbol = "[](bold cyan)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[](bold white)'   # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false           # disable in powershell
show_always = true

[os]
disabled = false
style = "bg:color_primary fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = " " # "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[hostname]
ssh_only = false
style = "bg:color_primary fg:color_fg0"
format = '[ $hostname ]($style)'

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
home_symbol = " "
read_only_style = "197"
read_only = "  "
format = "in [$path]($style)[$read_only]($read_only_style) "

[jobs]
symbol = '󰑮'
style = 'bold red'

[git_branch]
disabled = false
# symbol = " "
symbol = " "
format = "󰇙 [$symbol$branch]($style) "
truncation_length = 20
truncation_symbol = "…/"
style = "bold green"

[git_status]
disabled = true
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[terraform]
format = "󰇙 [󱁢]($style) [$workspace]($style) "

[vagrant]
format = "󰇙 [ vagrant $version]($style) "

[docker_context]
format = "󰇙 [ $context](bold blue) "

[helm]
format = "󰇙 [ $version](bold purple) "

[python]
symbol = " "
python_binary = "python3"

[nodejs]
format = "󰇙 [ $version](bold green) "
disabled = true

[ruby]
format = "󰇙 [ $version]($style) "

[kubernetes]
format = '󰇙 [ $context\($namespace\)](bold purple) '
disabled = true

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

[golang]
symbol = " "
disabled = true

[nix_shell]
symbol = ' '
# format = '󰇙 [$symbol$state$name]($style) '
format = '󰇙 [$symbol$state]($style) '
# symbol = '❄️ '
disabled = false
impure_msg = 'devbox'

[azure]
disabled = true
format = '󰇙 [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'
