#!/bin/bash

DISPLAYS=$(xrandr --listactivemonitors| grep 'Monitors:'| awk '{print $2}')
export DISPLAYS

if [ $DISPLAYS -gt 1 ]; then
  export PANEL_HEIGHT=31
else
  export PANEL_HEIGHT=46
fi

# If the process doesn't exists, start one in background
run() {
  if ! pgrep $1 ; then
    $@ &
  fi
}

# Just as the above, but if the process exists, restart it
run-or-restart() {
  if ! pgrep $1 ; then
    $@ &
  else
    pkill $1
    while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
    $@ &
  fi
}

run dunst
run sxhkd -c ~/.config/sxhkd/sxhkdrc_bspwm
#run sxhkd -s /run/user/1000/sxhkd.fifo
#run sxhkd-statusd /run/user/1000/sxhkd.fifo
run picom
run xbanish
run clipmenud
run emacs --daemon

~/.config/polybar/launch.sh 1

~/.config/bspwm/scripts/bspwm_clean_fullscreen &
pgrep bspswallow || ~/.config/bspwm/scripts/bspswallow &

wmname LG3D &

# bspc monitor -d      

# bspc monitor DP1 -d  
# bspc monitor DP2 -d  
# bspc monitor eDP1 -d  

case $DISPLAYS in
  1)
    # bspc monitor -d      
    bspc monitor -d 1 2 3 4 5 6
    ;;
  2)
    bspc monitor DP1 -d 1 2 3 4
    bspc monitor eDP1 -d 5 6
    ;;
  3)
    bspc monitor DP2 -d 1 2
    bspc monitor DP1 -d 3 4
    bspc monitor eDP1 -d 5 6
    ;;
esac

bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config automatic_scheme     longest_side

bspc config normal_border_color  "#343d46"
# bspc config focused_border_color "#6699cc"
bspc config focused_border_color "#fac863"

bspc config pointer_modifier     mod1

bspc config external_rules_command "/home/tuomo/.config/bspwm/scripts/external_rules"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Gcolor3 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# bspc rule -a Emacs desktop='^2'
bspc rule -a Firefox desktop='^3'
bspc rule -a Chromium desktop='^4'
bspc rule -a Brave-browser-beta desktop='^4'
# bspc rule -a Xephyr desktop='^5'

if [ $DISPLAYS -gt 1 ]; then
  bspc config border_width         1
  # sed -i 's/\( *font:[^"]*\)"\([^0-9]*\).*$/\1 "\210";/g' /home/tuomo/.config/rofi/themes/fonts.rasi
  # sed -i 's/^\(.*doom-font.*\)size [0-9]*\(.*\)$/\1size 14\2/g' ~/.doom.d/config.el
  # sed -i 's/^\(.*doom-variable-pitch-font.*\)size [0-9]*\(.*\)$/\1size 14\2/g' ~/.doom.d/config.el
  # sed -i 's/\(  size:\).*$/\1 10/g' ~/.config/alacritty/alacritty.yml
  # sed -i 's/^\(font_size\).*$/\1 10/g' ~/.config/kitty/kitty.conf
else
  bspc config border_width         2
  # sed -i 's/\( *font:[^"]*\)"\([^0-9]*\).*$/\1 "\218";/g' /home/tuomo/.config/rofi/themes/fonts.rasi
  # sed -i 's/^\(.*doom-font.*\)size [0-9]*\(.*\)$/\1size 23\2/g' ~/.doom.d/config.el
  # sed -i 's/^\(.*doom-variable-pitch-font.*\)size [0-9]*\(.*\)$/\1size 23\2/g' ~/.doom.d/config.el
  # sed -i 's/\(  size:\).*$/\1 9/g' ~/.config/alacritty/alacritty.yml
  # sed -i 's/^\(font_size\).*$/\1 9/g' ~/.config/kitty/kitty.conf
fi

# bsp-layout set tall 1 -- --master-size 0.5
# if [ $DISPLAYS -gt 1 ]; then
#   bsp-layout set wide 2 -- --master-size 0.8
#   bsp-layout set monocle 3
# else
#   bsp-layout set monocle 2
# fi

