#!/bin/bash

autorandr -c

DISPLAYS=$(xrandr --listactivemonitors| grep 'Monitors:'| awk '{print $2}')
export DISPLAYS

# If the process doesn't exists, start one in background
run() {
  if ! pgrep $1 ; then
    $@ &
  fi
}

# Just as the above, but if the process exists, restart it
run-or-restart() {
  if ! pgrep $1 ; then
    $@ &
  else
    pkill $1
    while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
    $@ &
  fi
}

# run dunst
pkill sxhkd ; sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
run picom
run clipmenud
# run volctl
# run cbatticon
# run volumeicon

# bspm -d &

~/.config/polybar/launch.sh 1

# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# ~/.local/bin/tint2-bar

# nm-applet --indicator &

# ~/.config/bspwm/scripts/bspwm_clean_fullscreen &
# pgrep bspswallow || ~/.config/bspwm/scripts/bspswallow &


# Change to a random wallpaper
# feh --no-fehbg --bg-scale $(find "/home/tuomo/Pictures/wallpapers" -xtype f | sort -R | head -1)

~/.fehbg &

# make the keyboard go faster
# xset r rate 300 40

# set keyboard layout and use caps lock as control and esc
# setxkbmap -layout fi -variant nodeadkeys -option 'caps:ctrl_modifier'
# killall xcape ; xcape -e 'Caps_Lock=Escape'

wmname LG3D &

case $DISPLAYS in
  1)
    bspc monitor -d 1 2 3 4 5 6
    bspc config -m eDP-1 top_padding 30
    ;;
  2)
    bspc monitor DP-3 -d 1 2 3 4
    bspc monitor eDP-1 -d 5 6
    bspc config -m DP-3 top_padding 30
0   bspc config -m eDP-1 top_padding 0
    ;;
  3)
    bspc monitor DP-3 -d 1 2
    bspc monitor DP-2 -d 3 4
    bspc monitor eDP-1 -d 5 6
    bspc config -m DP-3 top_padding 30
    bspc config -m DP-2 top_padding 0
    bspc config -m eDP-1 top_padding 0
    ;;
esac

bspc config window_gap           5
bspc config border_width         1
# bspc config border_width         0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config automatic_scheme     longest_side

bspc config normal_border_color  "#3b4252"
bspc config focused_border_color "#bc96da"

# bspc config normal_border_color  "#3b4252"
# bspc config focused_border_color "#bc96da"

bspc config pointer_modifier     mod1

# bspc config external_rules_command "/home/tuomo/.config/bspwm/scripts/external_rules"

bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Gcolor3 state=floating
bspc rule -a Gcolor2 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a spectacle state=floating center=on

bspc rule -a plasmashell state=floating center=off border=off
bspc rule -a Plasma state=floating
bspc rule -a plasma-desktop state=floating center=off border=off
bspc rule -a win7 state=floating
bspc rule -a krunner state=floating
bspc rule -a Kmix state=floating
bspc rule -a Klipper state=floating
bspc rule -a Plasmoidviewer state=floating
bspc rule -a lattedock state=floating center=off border=off
bspc rule -a krunner state=floating center=off border=off
