#!/usr/bin/perl

use strict;
use warnings;
use utf8;

my $ssid;
my $status;
my $icon = "";
my $full_text = "$icon";
my $short_text;

open (SSID, "iwconfig wlan0 | grep ESSID |") or die;
$ssid = <SSID>;
close(SSID);

# fail on unexpected output
if ($ssid !~ /ESSID:/) {
	die "$ssid\n";
}

if ($ssid =~ /ESSID:\"?([^\"]*)\"?/) {
	$status = "$1";
}

$status =~ s/^\s+|\s+$//g;
$full_text = "$icon  $status";
$short_text = "$full_text";

if ($status eq 'off/any') {
  $full_text = "OFFLINE";
}

print "$full_text\n";
print "$short_text\n";

if ($status eq 'off/any') {
  print "#cc6666\n";
}

exit(0);
