#!/bin/bash

op=$1
amount=${2:-'5'}

current_gap=$(bspc config -d focused window_gap)

case "$op" in
  grow) bspc config -d focused window_gap "$(($current_gap + $amount ))" ;;
  shrink) [ $(($current_gap - $amount)) -ge 0 ] && bspc config -d focused window_gap "$(($current_gap - $amount ))" ;;
  reset) bspc config -d focused window_gap 0 ;;
esac
