return {
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters = {
        markdownlint = {
          args = {
            "--disable",
            "MD001",
            "--disable",
            "MD045",
            "--disable",
            "MD010",
            "--disable",
            "MD012",
            "--disable",
            "MD004",
            "--disable",
            "MD026",
            "--disable",
            "MD031",
            "--disable",
            "MD034",
            "--disable",
            "MD041",
            "--disable",
            "MD033",
            "--disable",
            "MD013",
            "--disable",
            "MD037",
            "--disable",
            "MD022",
            "--disable",
            "MD009",
            "--disable",
            "MD032",
            "--",
          },
        },
      },
    },
  },
}
