# import = ["/home/tuomo/.config/alacritty/catppuccin-mocha.toml"]
import = ["/home/tuomo/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font"
# normal.family = "ComicShannsMono Nerd Font"
# normal.family = "CaskaydiaCove Nerd Font"
normal.style = "Regular"
size = 10
offset.y = 0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Super"

[shell]
program = "/usr/bin/fish"

[window]
decorations = "none"
padding = { x = 8, y = 0 }
opacity = 0.95
