#!/bin/bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -theme themes/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=" shutdown"
reboot="勒 restart"
lock=" lock"
suspend=" suspend"
logout=" logout"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
  $shutdown)
    ans=$($HOME/.config/rofi/scripts/confirm)
    if [[ $ans == "yes" ]]; then
      # xfce4-session-logout -h
      systemctl poweroff
    elif [[ $ans == "no" ]]; then
      exit
      # else
      #     rofi -theme ~/.config/rofi/themes/askpass.rasi -e "Available Options  -  yes / y / no / n"
    fi
    ;;
  $reboot)
    ans=$($HOME/.config/rofi/scripts/confirm)
    if [[ $ans == "yes" ]]; then
      # xfce4-session-logout -r
      systemctl reboot
    elif [[ $ans == "no" ]]; then
      exit
      # else
      #     rofi -theme ~/.config/rofi/themes/askpass.rasi -e "Available Options  -  yes / y / no / n"
    fi
    ;;
  $lock)
    # xflock4
    i3lock --color=#000000
    ;;
  $suspend)
    ans=$($HOME/.config/rofi/scripts/confirm)
    if [[ $ans == "yes" ]]; then
      # mpc -q pause
      # amixer set Master mute
      # xfce4-session-logout -s
      systemctl suspend
    elif [[ $ans == "no" ]]; then
      exit
      # else
      #     rofi -theme ~/.config/rofi/themes/askpass.rasi -e "Available Options  -  yes / y / no / n"
    fi
    ;;
  $logout)
    # xfce4-session-logout -l
    bspc quit
    # cinnamon-session-quit
    # ans=$($HOME/.config/rofi/scripts/confirm)
    # if [[ $ans == "yes" ]]; then
    #   # xfce4-session-logout -l
    #   # i3-msg exit
    #   # qtile-cmd -o cmd -f shutdown
    # elif [[ $ans == "no" ]]; then
    #   exit
    #   # else
    #   #     rofi -theme ~/.config/rofi/themes/askpass.rasi -e "Available Options  -  yes / y / no / n"
    # fi
    ;;
esac

