#!/bin/bash

rofi_command="rofi -theme themes/launcher.rasi"

sessions=$(tmux ls | sed -e 's/^\([^:]*\).*/\1/g')

chosen="$(echo -e "$sessions" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"

[[ ! -z "$chosen" ]] && $TERMINAL -e tmux new-session -A -s $chosen
